### PR TITLE
Demo PR

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
can we please start doing "proper" packages that are getting ready for releases, etc. So, please include dependencies, install targets etc. I'm happy to merge this now, but please keep the quality of PRs high.

**Comment by Jailander** [comment]
Hi yes this was temporary as we needed to have the latest demo ready for tomorrow when I'm back I'll document this propely and include the right dependencies licence and install targets

**Comment by pet1330** [comment]
We should probably start testing these before merging them as well, as a few of the recently commits  have been quite buggy...

**Comment by marc-hanheide** [comment]
Get @jailander to agree and write tests 😀

**Comment by Jailander** [comment]
This one only has the play twice bug as far as I know, once again I only made this PR so @pet1330 could have the demo running tomorrow for the visitors. Please if you see any other bug open an issue.

**Comment by marc-hanheide** [comment]
I'm just teasing you @jailander 😉

**Comment by Jailander** [comment]
Haha I know that, I was intrigued by the buggy part given that is my second PR to upstream and I wanted to know if @pet1330 had found another bug I had to fix I just sound grumpy because of the cold :P

**Comment by pet1330** [comment]
@Jailander I found another one... :stuck_out_tongue_winking_eye:  #11

**Pull request merged**
